# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'PureFlint' do
pod 'Alamofire', '~> 3.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'RealmSwift'
pod 'IBAnimatable', '~> 1.2'
pod "TextFieldEffects"
pod 'UIColor_Hex_Swift', '~> 1.9'

end

target 'PureFlintTests' do

end

target 'PureFlintUITests' do

end
